dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=kubectx
matrix:
  include:
  - env: TARGET=i686-unknown-linux-gnu
  - env: TARGET=i686-unknown-linux-musl
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=i686-apple-darwin
    os: osx
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
  - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
  - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
  - env: TARGET=aarch64-unknown-linux-gnu
  - env: TARGET=armv7-unknown-linux-gnueabihf
  - env: TARGET=mips-unknown-linux-gnu
  - env: TARGET=mips64-unknown-linux-gnuabi64
  - env: TARGET=mips64el-unknown-linux-gnuabi64
  - env: TARGET=mipsel-unknown-linux-gnu
  - env: TARGET=powerpc-unknown-linux-gnu
  - env: TARGET=powerpc64-unknown-linux-gnu
  - env: TARGET=powerpc64le-unknown-linux-gnu
  - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
before_install: set -e
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
    secure: XgnUIpoZd/3/Htm8oa5RST4lFKAIo/TYLdkpt/mrIgUTCeBn41hLxzKyNrjsNSXZj3oaqvN+CmzUgSFWvtqkavOdK+M9/5IDuSP8gOEkQmL6BIzdEYT/JwcTovipOi1znmI/2pbbdF8xu35T5VFsmISxccJbjAjduPvyQfLIoDfj6YnyPDNELskoO9SZNhN7oXi+WQM+U465SkwYzXMqJdGdIgx5jwvcAWlB/BgbNhePaag3Ul3s68DcIG7vIh/FnZMa2n3VgZQW2lTtDss4NjSWdFHwX5zaRajQgzsQa5sVqlS6ZI/CCKGibsO37NBG6OhS0HaWu/oNrfshSFHy5i5OMnK+IldpD5Y0WMGDjbAbCibQ0d7hMFvuYOoabwEBt6hhmZGN7+06EMq63Lg+JHMwHncpsMuUvL4peJOcHkO+lXiWVlNUphaaREquSynXblk/yMFGeCPcesLgUQNWuJ3TUjb8S/A341no1dN5BbF94cCSzNzjvghHEs8Ct+ANyu28MG8BW5kEhHINXddYa0BvaT+PC1fP1nOfuVghCxf8/oOwb35Xt55s1VmJYV+MNul/iUKiKAR8CUnJgi56HK+YpN0oye8MGPSuyYmw0v+QbfeN7Y7Zu+5/+VmPdH6ZjqjkgZXStnWPZmKAVmA9O7e/PuBBtFtChCUgp41IjVs=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - /^v\d+\.\d+\.\d+.*$/
  - master
notifications:
  email:
    on_success: never
